### ISSUE TITLE
Duplicate Section IDs in CRD docs

### ISSUE THREAD

**Issue by tobru** [vshn/appcat-user-docs#48]
In [crds.adoc](https://github.com/vshn/appcat-user-docs/blob/master/docs/modules/ROOT/pages/references/crds.adoc), which is generated by [the generator](https://github.com/vshn/appcat-user-docs/tree/master/generator), some sections do have the same ID, which is wrong and AsciiDoc complains accordingly:

```
{"level":"warn","time":1679916788312,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/references/crds.adoc","line":102},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"master","reftype":"branch","startPath":"docs"},"msg":"id assigned to section already in use: api-reference"}
{"level":"warn","time":1679916788410,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/references/crds.adoc","line":615},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"master","reftype":"branch","startPath":"docs"},"msg":"id assigned to section already in use: api-reference"}
```

_Possible solution:_

The [list template](https://github.com/vshn/appcat-user-docs/blob/master/generator/api-templates/gv-list.tpl#L7) might need to be enhanced to have a dynamic section ID.

**Comment by wejdross** [comment]
https://github.com/vshn/appcat-user-docs/pull/84
