### ISSUE TITLE
Broken "How to connect to Your instance" page

### ISSUE THREAD

**Issue by mhutter** [vshn/appcat-user-docs#87]
https://docs.appcat.ch/vshn-managed/postgresql/connect.html

- The title say "Untitled"
- All links to "Check how to find instanceNamespace" lead to a 404

**Comment by wejdross** [comment]
Fixed with: https://github.com/vshn/appcat-user-docs/commit/2ab6667b4e1900a592cd144495e2839ae6c61d5e

I'll wait for pipelines and verify if it works, then I'll close the issue

**Comment by wejdross** [comment]
works like a charm, but requires hard refresh to clear caches
